version: "3.6"
services:
  # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    env_file:
      - ./.private/postgres.env
    ports:
      - "5432:5432"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  # Backend
  smart-brain-api:
    env_file:
      - ./.private/smart-brain-api.env
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/smart-brain-api
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"
    # Heads up! Docker has updated this feature and now you don't need to define the links property in order for things to work - https://docs.docker.com/compose/networking/
    # links:
    #   - postgres
    #   - redis
